### ISSUE TITLE
Support 'oebv', 'scook' and 'HELBLING e-zone' libraries

### ISSUE THREAD

**Issue by KilianHech** [hampoelz/Digi4School2Pdf#1]
I can't download "Context@HTL", because it brings me to scook when I open the book abd there i can't download it.

**Comment by hampoelz** [comment]
Hey @KilianHech,
can you please write your steps? And what book are you trying to download?

**Comment by hampoelz** [comment]
@KilianHech thank you for the report!

Could you please write the address or token of the book?

**Comment by RCDANI123** [comment]
Problems with following books: (the books are part of the scoot and part of the  Helbling library :

https://www.helbling-ezone.com/ebook/1.6.1/#/ebook/d4s/more-3-enriched-wb-ebook?page=0

https://www.helbling-ezone.com/ebook/1.6.1/#/ebook/d4s/more-3-enriched-sb-ebook?page=0

https://www.scook.at/produkt/78294d44-cdb9-43eb-a685-605d7cb3d495

**Comment by hampoelz** [comment]
Unfortunately I don't have access to these books, but on the [Digi4School demo page](https://digi4school.at/demo) there are also demo books linked to these two libraries. So I'll have a look by time.

**Comment by nros** [comment]
The page seems to have an XML data of the book content encoded as JavaScript string inside a JSON object. The file is called `data.js` and looks something like the following. I assume, the name of the only property changes from book to book.
```JavaScript
ajaxData = {
  "cat152384.xml": "THE XML DATA"
};
```
Decoding and beautifying the encapsuled XML reveals something like this:
```XML
<assessmentItem
>
    <itemBody>
        <div id="content">
            <div id="contentblock">
                <ebook audiocontrols="false" autosave="false" cover="true" effects="false" offset="0" solution-hotspot-clone="true" title="Wortwechsel 1">
                    <pages>
                        <page audio="" height="2338" thumbnail="thumbnail-page-a7b602ad959320ad594cc78fe626bf11.jpg" url="page-a7b602ad959320ad594cc78fe626bf11.jpg" width="1653">
                            <hotspots />
                        </page>
                        <page audio="" height="2338" thumbnail="thumbnail-page-609296b478d83ec76e92fbf0c03a8b38.jpg" url="page-609296b478d83ec76e92fbf0c03a8b38.jpg" width="1653">
                            <hotspots>
                                <structure-node height="100" icon="multiple-items" id="cbb4c3eb-d775-4bce-828e-0303a0636d4a" left="0" ref="8a808b546566a6de016566a716be0002" title="Hotspot_2p_SB-Impressum" top="1184" width="100" />
                            </hotspots>
                        </page>
<!-- ... -->
                    </pages>
                    <toc>
                        <entry page="6" pagelabel="Seite 6" title="1 Starten">
                            <entry page="6" pagelabel="Seite 6" title="1. Starten">
                                <entry page="8" pagelabel="Seite 8" title="1.1 Lerntypen" />
                                <entry page="9" pagelabel="Seite 9" title="1.2 Arbeitsplatz und Lernumgebung" />
                                <entry page="10" pagelabel="Seite 10" title="1.3 Methoden zur Ideenfindung" /></entry>
                            <entry page="11" pagelabel="Seite 11" title="2. Schlüsselwörter" />
<!-- ... -->
                    </toc>
                </ebook>
            </div>
        </div>
    </itemBody>
</assessmentItem>
```


So. I was able to download all pages on bash with the XML stored as `pages.xml`.
```bash
(
let p=1
for url in `cat pages.xml| grep -E "<page.*url=" | sed -e 's#.*url="##g' -e 's#".*##g'`; do

    pageNum=$(printf "%03d\n" $p)

    curl "https://www.scook.at/cdn_proxy/ID_OF_BOOK_TAKEN_FROM_BROWSER/media/$url" \
  -H 'authority: www.scook.at' \
  -H 'pragma: no-cache' \
  -H 'cache-control: no-cache' \
  -H 'sec-ch-ua: "Chromium";v="91", " Not;A Brand";v="99"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36' \
  -H 'accept: image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8' \
  -H 'sec-fetch-site: same-origin' \
  -H 'sec-fetch-mode: no-cors' \
  -H 'sec-fetch-dest: image' \
  -H 'referer: NEED TO BE TAKEN FROM THE BROWSER' \
  -H 'accept-language: en-GB,en-US;q=0.9,en;q=0.8' \
  -H 'cookie: cookie_consent_closed=yes; _unity_web_session=TO_BE_TAKEN_FROM_THE_BROWSER' \
  -H 'dnt: 1' \
  -o page_$pageNum.jpg

    ((p=p+1))
done
)


```
These images can then be combined to a PDF - each image a single page - with the tool [`img2pdf`](https://gitlab.mister-muffin.de/josch/img2pdf)
```
img2pdf -o all-pages.pdf --pagesize A4 page_*.jpg 
```

Of course the TOC is not included as well as no meta data. Nevertheless, this could make it easier for you to figure out a way how to accomplish this with your application.

**Comment by hampoelz** [comment]
Thanks for pointing this out @nros.

I've looked at it and it's an interesting way to download pages from scook & co. However, it would be necessary to completely rewrite the download algorithm.

The current algorithm analyzes the page, finds the vector graphic of the page and writes it in a pdf. It works great on sites like digi4school, trauner-digibox and hpthek because they use the same backend. (Your method won't work on these pages)

Unfortunately, oebv, scook and helbling-ezone use a different backend, but display an image file like the pages above. Therefore, I plan to extend the current algorithm so that it can also analyze such pages. (Unfortunately these pages only provide pixel graphics)

**Comment by nros** [comment]
That sounds like a big effort :( Many thanks for your effort it's awesome to have this tool.

For those that are familiar with command line, this is the script I have used to download books from Helbing. Helbing does not enforce proper authentication like scook. All is needed is the URL to the book, as it contains a hash as ID, which the seem to feel hard enough to guess.

You need to do:

1. Use the developer tools to detect the any downloaded SVG and extract the URL, which is something like: `https://ebooks.helbling-ezone.com/ebook/books/<BOOK-ID>/pages/svg/1.svg`
2. Get the number of pages, eg. by jumping to the last page and get its number
3. All SVGs use the same base URI and are named `X.svg`, where 'X' is the page number
4. the SVGs reference other images with a relative path. So, all those images are extraced from the SVG, which is just plain text. These referenced images are then downloaded too.
5. The SVGs are converted to PDF page.
6. all PDF pages are merged into a single PDF in the end

The script works on MacOs and Linux and requires some additional utilities available on the command line.

* pdftk (https://gitlab.com/pdftk-java/pdftk)
* Cairo SVG https://cairosvg.org/

```bash
(
    BOOK_BASE_URL="https://ebooks.helbling-ezone.com/ebook/books/BOOK-ID/pages/svg/"
    LAST_PAGE=178


	downloadPart() {

	    source=$1
	    target=$2

	    dirName=$(dirname "$target")
	    [ ! -z "$dirName" ] && mkdir -p "$dirName"

	    curl "${BOOK_BASE_URL}$source" \
	        -H 'authority: ebooks.helbling-ezone.com' \
	        -H 'pragma: no-cache' \
	        -H 'cache-control: no-cache' \
	        -H 'sec-ch-ua: "Chromium";v="91", " Not;A Brand";v="99"' \
	        -H 'sec-ch-ua-mobile: ?0' \
	        -H 'upgrade-insecure-requests: 1' \
	        -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36' \
	        -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' \
	        -H 'sec-fetch-site: cross-site' \
	        -H 'sec-fetch-mode: navigate' \
	        -H 'sec-fetch-dest: object' \
	        -H 'referer: https://service.helbling.com/' \
	        -H 'accept-language: en-GB,en-US;q=0.9,en;q=0.8' \
	        -H 'dnt: 1' \
	        --compressed  --silent -o "$target"
  	}


    for p in {1..$LAST_PAGE}; do

      pageNum=$(printf "%03d\n" $p)

      echo "  * page $pageNum"
      downloadPart "${p}.svg" page_$pageNum.svg


      for img in `cat page_$pageNum.svg | sed -e 's#<#\
                  <#g' | grep -h "<image" | sed -e 's#.*xlink:href="##g' -e 's#".*##g'`; do
          echo "      --> part $img"
          downloadPart "${img}" "${img}"
      done


       echo "   => convert to PDF page"
       cairosvg -f pdf -o page_${pageNum}.pdf page_${pageNum}.svg
       rm -rf page_${pageNum}.svg $p/

   done


   echo "=> combining all pages"
   pdftk page_*.pdf cat output all-pages.pdf
   rm -f page_*.pdf
)

```

**Comment by nros** [comment]
@hampoelz  are you already having a plan about the needed changes? What is on your mind? I am willing to help.

I suggest to use separate classes as an abstraction to the download process and then add a big key/value registry where the keys are regular expression tests on the URL of the books. So, each URL can have its special downloader but class hierarchy makes it possible to have all common code in just one place.

Would you accept such changes are a PR? Maybe I have some spare time in 6 weeks - hopefully.

**Comment by nros** [comment]
OEBV
------
Downloading from oebv was easy too.
To make life easier, executing JavaScript in the browser is necessary. So, I guess, injecting some command would be very helpful to drive book detection and analysis.

All pages are images (PNG) with a fixed URL like: "https://portal.oebv.at/$BOOKID/content/pages/page_${PAGENR}/Scale4.png".  For the web, 4 zoom variants exist. "Scale_4.jpg" contains the highes resolution image.

The last page number to download can be detected on the browser console with:
```JavaScript
Object.getOwnPropertyNames(window.pageToTitle).pop()
```

The ID of the book can be detected with the following JavaScript code in browser console. This ID must be used for the download URLs.
```JavaScript
JSON.parse(document.getElementById("settings-json").innerHTML).annotations.sync.server.baseParameter.dienstId
```

**Comment by hampoelz** [comment]
1. @nros thanks for sharing this workaround script.

2. Yeah you're right, downloading from oebv is easy too. Basically, you open the webpage, find the image file, download it and write it to a PDF. That's what the download algorithm does. It doesn't take a lot of effort as it might sound ;). (The same principle works with scook and helbling-ezone) <br>
And thanks for your suggestion with the register, it will definitely help to keep things simple! 

3. I plan to make the D4S downloader a cross-platform app with a modular structure (more below), a more modern UI and of course add support for oebv, scook and helbling.

> **About cross platform support, a modular structure and the current state of development:**
> 
> Currently the downloader is using the [electron platform](https://github.com/electron/electron) as it's easy to load the webpages, get their content and process it using the nodejs backend. Unfortunately electron only supports desktop (Windows, Linux and MacOS). 
> 
> There is a similar platform called [capacitor](https://github.com/ionic-team/capacitor) that allows you to build native webapps for Android and IOS, but without the nodejs backend. It's also possible to bring such an app to the desktop using the [electron capacitor plugin](https://github.com/capacitor-community/electron). 
> 
> All well and good, but that doesn't help us much without nodejs backend. So I started coding a capacitor plugin to add the missing nodejs backend: [hampoelz/Capacitor-NodeJS](https://github.com/hampoelz/Capacitor-NodeJS). It's working great so far, but to make it completely cross-platform I'm currently working on adding support for the capacitor electron plugin. This makes it possible to run the app with just one code base on mobile (Android, iOS, iPadOS) and desktop (Windows, Linux, MacOS) operating systems.
> 
> At the moment I am waiting for the developer of the capacitor electron plugin to add a missing api feature, which the capacitor nodejs plugin needs. (capacitor-community/electron#137)
>  
> With all of this done, I'll make my [webapp wrapper](https://github.com/hampoelz/PWA-Wrapper-Desktop) cross-platform and port the D4S downloader to it.
> 
> It sounds complicated but with this modular structure its simpler to update all of my apps. The capacitor platform with the Electron and Nodejs plugin takes over the cross-platform part. The webapp wrapper handles page loading, user interface, update system, and more (So I have to code / update it once and all apps that use it will automatically reuse it). This means that everything in the digi4school downloader (and other apps) can be updated modularly and this repo will then only contain the actual download algorithm.

**Comment by hampoelz** [comment]
By the way @nros in your examples you suggested using hard links to the page's image file. When I started writing this downloader, I did the same thing. ([Digi4School2Pdf/blob/v0.1.2/app/downloader.js#L11](https://github.com/hampoelz/Digi4School2Pdf/blob/v0.1.2/app/downloader.js#L11)) But it soon turned out that there were books with other links to the source file. So in v0.2 I changed the download algorithm so that it finds the image element of the page and extracts the correct source file (https://github.com/hampoelz/Digi4School2Pdf/commit/e0adb230e0934fe20d6dde155f5b9e101ae3792d).

**Comment by nros** [comment]
Yes, your solution is superior. No, I prefer finding the proper links dynamically the way you did.
I agree with you, using hard coded download links is only a viable solution for scripting and just a start to gain more knowledge on the overall process. It is "quick and dirty" and not suitable for production use.

**Comment by hampoelz** [comment]
HELBLING e-zone library is now supported in the latest version. OEBV and Scook library support will be shipped in the next version.

**Comment by hampoelz** [comment]
OEBV and Scook libraries are now also support, you can update from store.
