### ISSUE TITLE
PWA wrapper dependency is missing - build/run failed

### ISSUE THREAD

**Issue by nros** [hampoelz/Digi4School2Pdf#12]
I can not build nor run.

Package `pwa-wrapper` is referenced as a local path. Hence it can not be found when trying to build on another machine. It is totally unclear, which PWA wrapper at which version this package depends on. Alternatively, add the file into this repository.

If the PWA wrapper is hosted on github, please use a github URL in package.json to reference the corrent package repository.
see: https://docs.npmjs.com/cli/v6/configuring-npm/package-json#github-urls

**Comment by hampoelz** [comment]
Oh yes you are right. I completely forgot. There were some issues with the PWA wrapper that needed fixing, so I switched to local path for faster debugging. As the whole PWA wrapper is still in very early stages.
