### ISSUE TITLE
Can't download books with empty title-tag

### ISSUE THREAD

**Issue by austrijanac** [hampoelz/Digi4School2Pdf#2]
Hello,

here is the book I can't download: https://a.digi4school.at/ebook/3038/

I guess it's because of the file extention.

Kind regards,
austrijanac

**Comment by hampoelz** [comment]
Hey @austrijanac  thanks for the bug report!

I've looked into it and it turned out that digi4school doesnt set a title for this book. Thats the reason why the browser displays a strange file name as title. So the downloader says there is no Book because the `<meta name="title">`-tag on the page is empty.

I plan to release a major update this summer containing a fix for this bug. If you need to download this book very soon, I'll fix this as soon as possible.

**Comment by austrijanac** [comment]
Thank you very much! It's not urgent.

**Comment by KimiRaiki** [comment]
Hello!

when i try to download an ebook it is not possible to download the vector file. When i choose the png file it works, but the pages in the downloaded pdf are croped (2/3). What can i do?
Greetings :)

**Comment by hampoelz** [comment]
Hey @KimiRaiki,

how did you downloaded the book via png? The downloader is currently only downloading the vector files. (from digi4school, trauner-digibox and hpthek).

Yeah the bug with cropped pages is already know, I'll fix it in the next release. If you need this fix anytime soon, I'll fix it asap.

**Comment by KimiRaiki** [comment]
When i download an e-book i can choose „vector graphic“ or „png“… some books aren‘t available to download as vector, so i have to choose png. 

It would be great, if you can fix the cropped pages soon :)

**Comment by hampoelz** [comment]
@KimiRaiki can you please send a screenshot of the option where you can choose vector or png?

**Comment by KimiRaiki** [comment]
![Uploading 66D7AB6A-0B36-4BE0-A0E2-47F55B9B4C4A.jpeg…]()

**Comment by hampoelz** [comment]
@KimiRaiki I can't open the picture. It looks like you haven't uploaded it completely. Would be great if you could upload it again.

**Comment by KimiRaiki** [comment]
![Uploading 42F2DA7A-0110-4724-B180-EC5942B0C6DD.jpeg…]()

**Comment by KimiRaiki** [comment]
![Uploading 680D3D25-C84E-482B-B1B6-A4B88218D212.png…]()

**Comment by KimiRaiki** [comment]
![Uploading 95DD02D9-FF4C-48F9-A278-D653C7A22563.png…]()

**Comment by KimiRaiki** [comment]
I tried it again, but it did not work. 
I‘ll try it again later on pc

**Comment by hampoelz** [comment]
You've to wait for the picture to be fully uploaded.

**Comment by hampoelz** [comment]
@austrijanac Fixed in latest version, you can update from store.
