### ISSUE TITLE
Cannot download E-Book-Plus Ebooks

### ISSUE THREAD

**Issue by confuxeon** [hampoelz/Digi4School2Pdf#7]
Currently Digi4School2Pdf is not able to download E-Book-Plus Ebooks. It says that no book has been found.

**Comment by hampoelz** [comment]
When you open the book, does it take you to a page like oebv, scook or helbling-ezone?

**Comment by hampoelz** [comment]
You can't download this book because the downloader only supports sites like digi4school, trauner-digibox or hpthek for now. I'll add support for oebv and other libraries soon as mentioned in #1.

**Comment by hampoelz** [comment]
@confuxeon The oebv library is now supported, you can update from store.
