### ISSUE TITLE
WayToGo 7 Ebook Download

### ISSUE THREAD

**Issue by psteinbacher** [hampoelz/Digi4School2Pdf#8]
I want to download the ebook but it sais "no book was found to download". 
It is an ebook plus, idk, is there an issue with such? Would be awsome if I could download it (other ebooks work fine)

**Comment by hampoelz** [comment]
You can't download this book because the downloader only supports sites like digi4school, trauner-digibox or hpthek for now. As fas as I know, the ebook you're trying to download is part of the oebv library. I'll add support for oebv and other libraries soon as mentioned in #1 or #5.

**Comment by hampoelz** [comment]
@psteinbacher The oebv library is now supported, you can update from store.

**Comment by psteinbacher** [comment]
Thank you very much!
